import {
  Callout,
  Card,
  CardBody,
  CardHeader,
  Code,
  Divider,
  Grid,
  H1,
  H2,
  H3,
  Pill,
  Row,
  Stack,
  Stat,
  Table,
  Text,
  useHostTheme,
} from 'cursor/canvas';

const phaseRows = [
  [
    '1. Profile and prepare inputs',
    'Load the 2.7 demo dump into legacy_27_raw; boot the O3 RefApp baseline with CIEL loaded into openmrs; compute schema diff and Liquibase cost.',
    'M2-A',
  ],
  [
    '2. Freeze reviewed mapping inputs',
    'Accepted FHIR ConceptMap remains the terminology source of truth; seed_emit expands it into SQLMesh CSV seeds.',
    'M2-C',
  ],
  [
    '3. Materialize SQLMesh models',
    'SQLMesh reads legacy_27_raw + openmrs + seeds and writes refapp_28_demo through seed, staging, terminology, clinical, module, and audit-view models.',
    'M2-D/E',
  ],
  [
    '4. Run conformance gates',
    'The harness invokes sqlmesh plan, run, audit; custom audits emit zero rows on pass and record-level failures on fail.',
    'M2-E',
  ],
  [
    '5. Load via dlt → openmrs_test_dlt → promote → openmrs_test',
    'dlt reads sqlmesh__refapp_28_demo physical snapshots and lands them in a staging schema; promote copies clean rows (no _dlt_* columns) into the actual OpenMRS DB. See research.md §R-load-pattern.',
    'M2-F (Phase 5D)',
  ],
  [
    '6. Validate downstream',
    'orphan-fk-check (FR-013), import-smoke (REST + FHIR readback), dump-loaded for portable .sql.gz, then chartsearchai live (M2-F.1).',
    'M2-F / M2-F.1',
  ],
];

const sqlmeshLayers = [
  [
    'config.yaml',
    'Gateway and variables',
    'Pins the harness gateway to MariaDB and declares legacy_27_raw, openmrs, and refapp_28_demo schemas.',
  ],
  [
    'models/seeds/',
    'Reviewed and emitted inputs',
    'concept_translation.csv from ConceptMap; module_table_policy.csv for legacy-only module tables.',
  ],
  [
    'models/staging/',
    '1:1 source staging',
    'Staging models mirror selected legacy tables into the SQLMesh graph so downstream models can depend on stable names. ~39 stg_* models.',
  ],
  [
    'models/terminology/',
    'Concept rebind + FK reconciliation maps',
    'concept_rebind exposes obs with target_concept_ids via the bridge rule; <entity>_map seeds document legacy↔openmrs ID translation.',
  ],
  [
    'models/clinical/',
    'Clinical remap and promotion',
    'Rebound obs stays in clin__obs; selected obs rows promote into drug_order, conditions, allergy, test_order; clin__orders is the parent of drug_order/test_order (Hibernate joined-table inheritance).',
  ],
  [
    'models/modules/',
    'Module-table policy',
    'Legacy-only module tables are carried forward (16 generated by harness/transform/gen_modules.py from module_table_policy.csv).',
  ],
  [
    'models/audit_views/',
    'Equivalence-decorated mart UNION',
    'aud__equivalence_decoration UNIONs every promoted + kept row with its policy_bucket and equivalence label for the sampler.',
  ],
  [
    'audits/',
    'Acceptance gates',
    'Concept coverage, FK closure, policy bucket coverage, uniqueness, not-null, per-mart row-count floors (5D fix).',
  ],
];

const reviewerRows = [
  [
    'Concept identity bridge',
    'ConceptMap bridge rule plus concept_translation.csv',
    'Every legacy concept_id gets a target CIEL UUID via RPAD(concept_id, 36, A); obs-referenced concepts must have 100% coverage.',
  ],
  [
    'Structural promotions',
    'clinical/drug_order.sql, conditions.sql, allergy.sql, test_order.sql',
    'Only four typed-table promotion rules are reviewed; residual obs remains in obs for provenance and chartsearchai indexing.',
  ],
  [
    'Module table decisions',
    'module_table_policy.csv and modules/* models',
    'Each legacy-only module table needs an explicit carry-forward, drop, install-module, or remap policy with rationale.',
  ],
  [
    'Pre-staged Liquibase work',
    'clinical/modules models plus liquibase cost report',
    'Expensive post-2.7 changesets can be produced directly by SQLMesh so import startup does not pay full-table copy cost.',
  ],
  [
    'Audit failures',
    'audits/*.sql and transform artifacts',
    'A failing custom audit emits the exact concept, row, or FK problem; aggregate counts alone are not accepted evidence.',
  ],
];

const commandRows = [
  ['Seed emit', 'python -m harness.conceptmap.seed_emit --conceptmap datasets/mappings/openmrs-2.7-to-2.8.conceptmap.json'],
  ['Static parse', 'sqlmesh -p datasets/transforms/sqlmesh parse'],
  ['Plan + apply', 'sqlmesh -p datasets/transforms/sqlmesh plan prod --no-prompts --auto-apply'],
  ['Audit', 'sqlmesh -p datasets/transforms/sqlmesh audit'],
  ['Hermetic test surface', 'make loadtest-up   (drops + recreates openmrs_test and openmrs_test_dlt from openmrs canvas)'],
  ['Load (dlt + promote)', 'make load-test   (refapp_28_demo snapshots → openmrs_test_dlt → openmrs_test)'],
  ['Post-load FK audit (FR-013)', 'make orphan-fk-check'],
  ['REST/FHIR readback (FR-014)', 'make import-smoke'],
  ['Portable SQL dump for sharing', 'make dump-loaded   (→ artifacts/<run>/transform/refapp_28_demo.sql.gz)'],
];

const outputRows = [
  [
    'refapp_28_demo',
    'SQLMesh user-facing schema (views over snapshot tables)',
    'Queryable analytical state — what the audits + sampler read from.',
  ],
  [
    'sqlmesh__refapp_28_demo',
    'SQLMesh physical layer (versioned snapshot tables)',
    'Where the dlt loader actually reads from. The user-facing views are thin pointers at these snapshots.',
  ],
  [
    'openmrs_test_dlt',
    'Staging schema written by dlt (with _dlt_* metadata columns)',
    'dlt\'s metadata columns are not suppressible; isolating them here keeps the OpenMRS schema clean. See research.md §R-load-pattern.',
  ],
  [
    'openmrs_test',
    'Final OpenMRS-shape schema (Hibernate-compatible)',
    'What the live RefApp backend points at. NO _dlt_* columns. Iteration target — promote to openmrs when ready.',
  ],
  [
    'refapp_28_demo.sql.gz',
    'Portable dump artifact (shareable like the original 2.7 corpus)',
    'Produced by make dump-loaded. ~39 MB; load via `zcat ... | mariadb -u root -p`.',
  ],
  [
    'transform.report.json + import-smoke/report.json + orphan-fk-report.json',
    'Run-level evidence',
    'Per-record evidence trail required by constitution III and FR-013/FR-014.',
  ],
];

function FlowDiagram() {
  const theme = useHostTheme();
  const nodes = [
    { title: 'legacy_27_raw', detail: '2.7 demo dump', x: 20, y: 36 },
    { title: 'openmrs', detail: 'CIEL-loaded O3 baseline', x: 20, y: 130 },
    { title: 'ConceptMap', detail: 'reviewed mapping grammar', x: 20, y: 224 },
    { title: 'Seed emit', detail: 'concept_translation.csv', x: 245, y: 224 },
    { title: 'SQLMesh graph', detail: 'seed → staging → terminology → clinical → modules → audit_views', x: 245, y: 130 },
    { title: 'Audits', detail: 'zero rows on pass', x: 510, y: 130 },
    { title: 'refapp_28_demo', detail: 'views over sqlmesh__* snapshots', x: 510, y: 36 },
    { title: 'dlt loader', detail: 'reads physical snapshots', x: 775, y: 130 },
    { title: 'openmrs_test_dlt', detail: 'staging schema (with _dlt_*)', x: 775, y: 36 },
    { title: 'promote step', detail: 'clean column copy', x: 1010, y: 130 },
    { title: 'openmrs_test', detail: 'OpenMRS-shape target', x: 1010, y: 36 },
    { title: 'Validate', detail: 'orphan-fk + smoke + sample', x: 1010, y: 224 },
  ];
  const edges = [
    [0, 4],
    [1, 4],
    [2, 3],
    [3, 4],
    [4, 5],
    [4, 6],
    [5, 7],
    [6, 7],
    [7, 8],
    [7, 9],
    [8, 9],
    [9, 10],
    [10, 11],
  ];
  const width = 1220;
  const height = 320;
  const nodeW = 178;
  const nodeH = 64;

  return (
    <svg role="img" aria-label="Feature 002 SQLMesh transformation flow" width="100%" viewBox={`0 0 ${width} ${height}`} style={{ display: 'block' }}>
      <defs>
        <marker id="sqlmesh-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse">
          <path d="M 0 0 L 10 5 L 0 10 z" fill={theme.stroke.secondary} />
        </marker>
      </defs>
      {edges.map(([from, to], i) => {
        const a = nodes[from];
        const b = nodes[to];
        const x1 = a.x + nodeW;
        const y1 = a.y + nodeH / 2;
        const x2 = b.x;
        const y2 = b.y + nodeH / 2;
        const midX = (x1 + x2) / 2;
        return (
          <path
            key={`e-${i}`}
            d={`M ${x1} ${y1} C ${midX} ${y1}, ${midX} ${y2}, ${x2 - 6} ${y2}`}
            fill="none"
            stroke={theme.stroke.secondary}
            strokeWidth={1.2}
            markerEnd="url(#sqlmesh-arrow)"
          />
        );
      })}
      {nodes.map((n, i) => {
        const accent = n.title === 'SQLMesh graph' || n.title === 'refapp_28_demo';
        return (
          <g key={n.title}>
            <rect
              x={n.x}
              y={n.y}
              width={nodeW}
              height={nodeH}
              rx={8}
              fill={accent ? theme.fill.secondary : theme.bg.elevated}
              stroke={accent ? theme.accent.primary : theme.stroke.primary}
              strokeWidth={accent ? 1.5 : 1}
            />
            <text x={n.x + 12} y={n.y + 26} fontSize={13} fill={theme.text.primary} style={{ fontFamily: 'inherit', fontWeight: 600 }}>
              {n.title}
            </text>
            <text x={n.x + 12} y={n.y + 47} fontSize={11} fill={theme.text.secondary} style={{ fontFamily: 'inherit' }}>
              {n.detail}
            </text>
            {i === 4 && (
              <text x={n.x + 12} y={n.y + 86} fontSize={10.5} fill={theme.text.tertiary} style={{ fontFamily: 'inherit' }}>
                plan / run / audit
              </text>
            )}
          </g>
        );
      })}
    </svg>
  );
}

export default function SQLMeshTransformationFlow() {
  return (
    <Stack gap={18}>
      <Stack gap={8}>
        <Row gap={8} wrap>
          <Pill tone="info" active>Feature 002</Pill>
          <Pill tone="info" active>SQLMesh</Pill>
          <Pill tone="success" active>Deterministic transform</Pill>
          <Pill tone="warning" active>Reviewer-gated</Pill>
        </Row>
        <H1>How Feature 002 Uses SQLMesh</H1>
        <Text tone="secondary">
          Feature 002 turns the OpenMRS 2.7 demo dump into a 2.8/O3-compatible corpus by using SQLMesh as the
          deterministic SQL-to-SQL transformation layer. SQLMesh does not decide mappings; it executes reviewed
          ConceptMap and module-policy decisions against MariaDB and produces a reproducible target schema.
        </Text>
      </Stack>

      <Grid columns={4} gap={12}>
        <Stat value="5" label="Schemas in play: legacy_27_raw, openmrs, refapp_28_demo, openmrs_test_dlt, openmrs_test" tone="info" />
        <Stat value="7" label="SQLMesh layers: seeds, staging, terminology, clinical, modules, audit_views, audits" tone="info" />
        <Stat value="5" label="Promotion models: drug_order, conditions, allergy, test_order + clin__orders parent" tone="success" />
        <Stat value="0" label="Audit rows required for acceptance" tone="success" />
      </Grid>

      <Callout tone="info" title="One-sentence version">
        The harness freezes reviewed mapping decisions into CSV seeds, SQLMesh materializes the remapped clinical corpus
        into <Code>refapp_28_demo</Code> (views over physical <Code>sqlmesh__refapp_28_demo</Code> snapshots), then{' '}
        <Code>dlt</Code> loads those snapshots into <Code>openmrs_test_dlt</Code> and a promote step copies clean rows
        (no <Code>_dlt_*</Code> columns) into the live <Code>openmrs_test</Code> schema for the real RefApp to serve.
      </Callout>

      <Card>
        <CardBody>
          <FlowDiagram />
        </CardBody>
      </Card>

      <H2>Process In Five Phases</H2>
      <Table
        headers={['Phase', 'What happens', 'Milestone']}
        rows={phaseRows}
        striped
      />

      <Divider />

      <H2>The SQLMesh Project Shape</H2>
      <Text tone="secondary">
        The project root is <Code>datasets/transforms/sqlmesh/</Code>. SQLMesh is intentionally thin: model files are
        reviewable SQL, seeds are deterministic inputs, and audits are the acceptance gates.
      </Text>
      <Table
        headers={['Layer', 'Role', 'Feature 002 usage']}
        rows={sqlmeshLayers}
        striped
      />

      <Grid columns="1fr 1fr" gap={14}>
        <Card>
          <CardHeader>Inputs SQLMesh Reads</CardHeader>
          <CardBody>
            <Stack gap={8}>
              <Text><Text weight="semibold">legacy_27_raw:</Text> the loaded 2.7 demo dump, treated as read-only source.</Text>
              <Text><Text weight="semibold">openmrs:</Text> the clean O3/Core 2.8 baseline after deterministic CIEL import.</Text>
              <Text><Text weight="semibold">concept_translation.csv:</Text> emitted from the accepted ConceptMap; not hand-edited.</Text>
              <Text><Text weight="semibold">module_table_policy.csv:</Text> reviewed policy for legacy-only module tables.</Text>
            </Stack>
          </CardBody>
        </Card>
        <Card>
          <CardHeader>Outputs SQLMesh Produces</CardHeader>
          <CardBody>
            <Stack gap={8}>
              <Text><Text weight="semibold">refapp_28_demo:</Text> materialized MariaDB target schema.</Text>
              <Text><Text weight="semibold">clinical typed tables:</Text> drug_order, conditions, allergy, test_order synthesized from obs where rules match.</Text>
              <Text><Text weight="semibold">rebound obs:</Text> residual observations remain available for provenance and chartsearchai indexing.</Text>
              <Text><Text weight="semibold">audit evidence:</Text> failing concepts, FK gaps, or policy gaps are emitted as rows.</Text>
            </Stack>
          </CardBody>
        </Card>
      </Grid>

      <Divider />

      <H2>Reviewer Surface</H2>
      <Text tone="secondary">
        The key design goal is to keep human review small and explicit. Reviewers do not inspect every row in the dump;
        they inspect the deterministic rules and the evidence rows that prove those rules covered the corpus.
      </Text>
      <Table
        headers={['Decision surface', 'Artifact', 'What reviewer checks']}
        rows={reviewerRows}
        striped
      />

      <H2>Command Flow</H2>
      <Table
        headers={['Step', 'Command or action']}
        rows={commandRows}
        striped
      />

      <H2>Run Artifacts</H2>
      <Table
        headers={['Artifact', 'What it is', 'Why it matters']}
        rows={outputRows}
        striped
      />

      <Divider />

      <H2>Load-Bearing Rules</H2>
      <Grid columns="1fr 1fr 1fr" gap={14}>
        <Card>
          <CardHeader>Concept Identity Bridge</CardHeader>
          <CardBody>
            <Text>
              The accepted bridge rule maps legacy concept <Code>N</Code> to the seeded CIEL concept whose UUID is
              <Code> RPAD(N, 36, 'A')</Code>. The seed CSV expands this to one row per legacy concept, while the audit
              requires every obs-referenced concept to be covered.
            </Text>
          </CardBody>
        </Card>
        <Card>
          <CardHeader>Obs Preservation</CardHeader>
          <CardBody>
            <Text>
              Promotion does not erase provenance. Selected obs rows create typed records, while residual obs remains
              in <Code>clin__obs</Code>. This keeps chartsearchai retrieval and reviewer traceability intact.
            </Text>
          </CardBody>
        </Card>
        <Card>
          <CardHeader>Determinism Boundary</CardHeader>
          <CardBody>
            <Text>
              SQLMesh gives content-fingerprinted model versions and reproducible materialization, but the harness must
              keep seeds, UUID generation, dump flags, and runtime inputs deterministic too.
            </Text>
          </CardBody>
        </Card>
      </Grid>

      <Callout tone="warning" title="Known gap — UUID v5 deferred">
        Promoted-row <Code>uuid</Code> columns in <Code>clinical/drug_order.sql</Code> and siblings currently use
        non-deterministic <Code>UUID()</Code>. Research.md §R-typed-table-promotion Q2 specifies UUID v5 from row hash;
        this is acknowledged as a deferred gap. Idempotency is asserted via per-table row counts + content checksums in{' '}
        <Code>materialized_outputs[]</Code> rather than dlt&apos;s state hash to keep the SC-004 contract honest in the
        meantime. <Code>order_id</Code> uses <Code>obs.obs_id</Code> directly (deterministic, traceable).
      </Callout>

      <Callout tone="info" title="Why SQLMesh ends at refapp_28_demo and dlt picks up from there">
        SQLMesh stores user-facing schemas as views over versioned snapshot tables — perfect for analytical workflows
        but produces <Code>165 KB</Code> of view DDL when you <Code>mariadb-dump</Code> the user schema. dlt is the
        Tobiko-endorsed handover tool that picks up from the physical snapshot layer and writes to OLTP destinations
        with PK-based idempotency. Each tool stays in its lane; see research.md §R-load-pattern.
      </Callout>

      <Callout tone="success" title="What SQLMesh buys us here">
        Feature 002 gets a reviewed, standards-based transform graph instead of ad hoc SQL scripts: the mapping decisions
        are externalized, the executable shape is visible in model files, and the acceptance gates are executable with
        <Code> sqlmesh plan</Code>, <Code> run</Code>, and <Code> audit</Code>.
      </Callout>
    </Stack>
  );
}
