"""Generate one SQLMesh model per row in
``datasets/transforms/sqlmesh/seeds/module_table_policy.csv``.

Introspects each table's primary key from ``legacy_27_raw`` so the
emitted model declares a real ``grain`` (SQLMesh rejects empty grain
lists). Falls back to the first column if no PK is declared.

Per ``contracts/sqlmesh_project.profile.md`` §Project layout, every
module-owned legacy table that's flagged in the policy seed must have
a corresponding model under ``datasets/transforms/sqlmesh/models/modules/``.

Currently only one policy is materialized:

  - ``carry-forward``: SELECT * FROM legacy_27_raw.<table>, tagged
    ``policy_bucket:orphan-carry-forward``. Preserves the table + rows
    verbatim in ``refapp_28_demo`` so the modern RefApp boots with the
    orphan tables present (matches real OpenMRS distro upgrade behavior
    per spec FR-012).

Other policies (drop, install-module, remap) are author-on-demand.

Re-runnable: regenerates the full set, overwriting in place. Use after
editing ``module_table_policy.csv``.

Usage:

  uv run python -m harness.transform.gen_modules
"""

from __future__ import annotations

import csv
from pathlib import Path

from harness.profile.db import DBConfig, query


SEED_PATH = Path("datasets/transforms/sqlmesh/seeds/module_table_policy.csv")
MODELS_DIR = Path("datasets/transforms/sqlmesh/models/modules")
LEGACY_SCHEMA = "legacy_27_raw"
TARGET_SCHEMA = "refapp_28_demo"

# SQLMesh constructs snapshot table names of the form
# "<target_schema>__mod__<table_name>__<10-digit-hash>". MariaDB caps
# identifiers at 64 chars. Schema `refapp_28_demo` (14 chars) + fixed
# overhead `__mod____<10>` (21 chars) = 35 chars; table names must
# fit in the remaining 29. We allow up to 28 to keep one char of
# buffer for SQLMesh hash variations. Tables over the threshold are
# skipped with a clear log line; document the orphan in the
# review.md companion.
MAX_TARGET_TABLE_NAME = 28


def _primary_key_cols(cfg: DBConfig, table: str) -> list[str]:
    rows = query(cfg, f"""
        SELECT column_name FROM information_schema.key_column_usage
        WHERE table_schema='{cfg.database}' AND table_name='{table}'
          AND constraint_name='PRIMARY'
        ORDER BY ordinal_position
    """)
    return [r[0] for r in rows if r and r[0]]


def _first_column(cfg: DBConfig, table: str) -> str:
    rows = query(cfg, f"""
        SELECT column_name FROM information_schema.columns
        WHERE table_schema='{cfg.database}' AND table_name='{table}'
        ORDER BY ordinal_position LIMIT 1
    """)
    if not rows or not rows[0]:
        raise RuntimeError(f"table {table!r} has no columns in {cfg.database}")
    return rows[0][0]


def resolve_grain(cfg: DBConfig, table: str) -> str:
    """Return the `grain (...)` body for ``table``. PK if declared,
    otherwise the first column as a best-effort grain."""
    pk = _primary_key_cols(cfg, table)
    if pk:
        return ", ".join(pk)
    return _first_column(cfg, table)


CARRY_FORWARD_TEMPLATE = """\
MODEL (
  name {target}.mod__{table},
  kind VIEW,
  description '{description}',
  tags (policy_bucket:orphan_carry_forward),
  grain ({grain})
);

-- Auto-generated by harness/transform/gen_modules.py from
-- seeds/module_table_policy.csv. Do NOT edit by hand — re-run the
-- generator instead.

SELECT * FROM {legacy}.{table};
"""


def render_carry_forward(table: str, rationale: str, grain: str) -> str:
    description = (
        f"Carry-forward orphan: legacy module-owned table preserved verbatim "
        f"in the materialized output. {rationale}"
    ).replace("'", "''")
    return CARRY_FORWARD_TEMPLATE.format(
        target=TARGET_SCHEMA,
        legacy=LEGACY_SCHEMA,
        table=table,
        description=description,
        grain=grain,
    )


def generate(
    seed_path: Path = SEED_PATH, out_dir: Path = MODELS_DIR
) -> tuple[list[Path], list[str]]:
    """Generate one model file per policy row.

    Returns ``(written, skipped)`` — paths written + table names skipped
    because their target identifier would exceed MariaDB's 64-char limit.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    cfg = DBConfig.from_env(database=LEGACY_SCHEMA)
    written: list[Path] = []
    skipped: list[str] = []
    with seed_path.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            table = row["table_name"].strip()
            policy = row["policy"].strip()
            rationale = row.get("rationale", "").strip() or "no rationale recorded"
            if len(table) > MAX_TARGET_TABLE_NAME:
                skipped.append(table)
                continue
            if policy == "carry-forward":
                grain = resolve_grain(cfg, table)
                sql = render_carry_forward(table, rationale, grain)
            else:
                raise NotImplementedError(
                    f"policy {policy!r} not yet supported by gen_modules.py; "
                    f"add a template before regenerating"
                )
            target_path = out_dir / f"{table}__{policy}.sql"
            target_path.write_text(sql, encoding="utf-8")
            written.append(target_path)
    return written, skipped


def main() -> int:
    written, skipped = generate()
    print(f"Wrote {len(written)} module models to {MODELS_DIR}")
    for p in written:
        print(f"  {p}")
    if skipped:
        print(f"\nSkipped {len(skipped)} tables (name > {MAX_TARGET_TABLE_NAME} chars; "
              f"MariaDB 64-char identifier limit):")
        for t in skipped:
            print(f"  {t}  ({len(t)} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
